### ISSUE TITLE
Bad log level for NSCA packet information log

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-nsca#8]
As of https://github.com/naparuba/shinken/issues/1625, ... should change log level to debug for NSCA packet information.

See : https://github.com/shinken-monitoring/mod-nsca/blob/master/module/module.py#L171

**Comment by mohierf** [comment]
@naparuba : you are referenced as owner. Do you mind if I update the version and publish this module ?

**Comment by naparuba** [comment]
? that's David now cf: http://shinken.io/package/nsca

**Comment by mohierf** [comment]
Oups ! Sorry ...

@ddurieux : what about publishing a new version ?

**Comment by ddurieux** [comment]
Yes if you want, can you increment the version and after I publish it ;)
